### ISSUE TITLE
"Open in Browser" no longer a thing

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/scraping-kickstarter#23]
This lesson says to choose "open in browser" from right-clicking on a file.  It also says to run `open fixtures/kickstarter.html` which in IDE 2.4.2 gives an error.

CC: @aturkewi

**Comment by curiositypaths** [comment]
Hi there, 

Thank you for the correction. We updated the README to provides the steps required to open the file from the Learn IDE.

As always, thanks for contributing! 💙
