### ISSUE TITLE
IDE unresponsive 

### ISSUE THREAD

**Issue by gURLmeetsCode** [learn-co-curriculum/scraping-kickstarter#24]
IDE is unresponsive and buggy. This has been an ongoing issue for 3 weeks now. This is negatively impacting my curriculum progress.

**Comment by curiositypaths** [comment]
Hi there, 

Thank you for notifying us about the issue. We updated the fixture to prevent any sluggishness between the IDE and this lesson.

As always, thanks for contributing! 💙
