### ISSUE TITLE
IDE crashes on kickstarter html

### ISSUE THREAD

**Issue by anglinchristina** [learn-co-curriculum/scraping-kickstarter#25]
I'm running v2.5.2 of the Learn IDE.  Every time I open the kickstarter.html file, the Editor freezes and then quits.

**Comment by curiositypaths** [comment]
Hi there, 

Thank you for notifying us about the issue. We updated the fixture to prevent any sluggishness between the IDE and this lesson.

As always, thanks for contributing! 💙
