### ISSUE TITLE
Seems slow and buggy...

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/scraping-kickstarter#27]
I tried resetting the browser multiple times and reloading IDE multiple times. The lab still behaves oddly. It crashes frequently and will raise errors such as "undefined variable kickstarter" even when the variable is clearly defined. Please check and debug.

**Comment by curiositypaths** [comment]
Hi there, 

Thank you for notifying us about the issue. We updated the fixture to prevent any sluggishness between the IDE and this lesson.

As always, thanks for contributing! 💙
