### ISSUE TITLE
"Select "open in browser" from the menu that appears." Option not available in Learn IDE.

### ISSUE THREAD

**Issue by alexcrisan** [learn-co-curriculum/scraping-kickstarter#28]
This option does not exist when right clicking in the .html file, or right clicking the file name itself in the tree view. Right clicking anything also seems to be freezing up Learn IDE.

**Comment by curiositypaths** [comment]
Hi there, 

Thank you for the correction. We updated the README to provides the steps required to open the file from the Learn IDE.

As always, thanks for contributing! 💙
