### ISSUE TITLE
Add terminal key shortcuts for use in Pry

### ISSUE THREAD

**Issue by sammarcus** [learn-co-curriculum/scraping-kickstarter#3]
This is the first time a student runs pry not through rspec and invokes it on their own. It returns an entire HTML page and the lab doesn't explain how to navigate around the response.

It behaves like it "froze" and doesn't accept any input. `Command` + `L` seems to work, if you follow it with a `Q`.

**Comment by AnnJohn** [comment]
Iceboxing for now
