### ISSUE TITLE
The instructions for opening the fixtures/kickstarter.html in a web browser don't appear to  work.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/scraping-kickstarter#30]
Hello. I need to preface this by mentioning that I am using the Learn IDE in Google Chrome on a Windows OS. That having been said, the instructions for opening the fixtures/kickstarter.html file in my web browser don't work, for some reason. I am able to access the file in my web browser, but not with the instructions in the README.

Here are the instructions that don't work: 

"If you are using the Learn IDE right click on the kickstarter.html file and select Show in Finder. Once Finder opens double click kickstarter.html to view the file inside your default web browser. If you are not using the Learn IDE, try open kickstarter.html inside your text editor and right-click anywhere on the page to select open in browser from the menu that appears."

The trouble is, no matter where I right-clicked (on the file name, inside of the file, etc.), I did not see "Show in Finder" or "Open in Browser" among my available menu options. I suspect that the "Show in Finder" option is only available for Apple computers.

Currently, the only way that I can open the fixtures/kickstarter.html file inside of my browser is by typing httpserver into the Learn IDE terminal, going to the link provided, and navigating to fixtures/kickstarter.html from there. However, the instructions in the README don't mention httpserver as an option.

Thanks for looking into this! Please let me know if you need any more information.

Regards,

Sdcrouse

**Comment by Sdcrouse** [comment]
Update: A similar problem happens in the "Selecting the Projects" section.

**Comment by drakeltheryuujin** [comment]
Hi @Sdcrouse,

Thank you for your feedback. The README has been updated with your suggestions. 

As always, thanks for contributing! 💙

**Comment by Sdcrouse** [comment]
You're welcome! And thanks a lot for fixing that!
