### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by lorena57** [learn-co-curriculum/scraping-kickstarter#31]
"and add binding.pry after the last line."  
Super confused as to what the last line was.  I placed my binding pry on the line after kickstarter = Nokogiri::HTML(html)

Example:

def create_project_hash
  html = File.read('fixtures/kickstarter.html')
  kickstarter = Nokogiri::HTML(html)
binding.pry
end

**Comment by maxwellbenton** [comment]
Hi @lorena57,

Thank you for spotting this and providing feedback. You're correct on the placement of `binding.pry`. We've added a code snippet to clarify these instructions. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
